version: "3.6"

services:
  mysql:
    build: "./mysql"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret"
      MYSQL_DATABASE: "devdb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpassword"
    ports:
      - "33060:3306"
  book:
    build: "."
    command: "ClickPhonebook"
    depends_on:
    - "mysql"
    ports:
    - "8081:8080"
    environment:
      MYSQL_DATABASE: "devdb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpassword"
      HTTP_PROXY: ""
